MODEL:
  NUM_CLASSES: 12
  LOSS: "mse_loss"

INPUT:
  SIZE_TRAIN: 800
  SIZE_TEST: 800
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 32

TEST:
  IMS_PER_BATCH: 32

DATASETS:
  TRAIN: "viewds"
  TEST: "viewds"
  NUM_ELEMENTS: 1000

OUTPUT_DIR: "logs/viewds_baseline"
